server:
  port: 8081

dubbo:
  application:
    name: user-provider
  registry:
    address: zookeeper://114.96.67.201:2181
  protocol:
    name: dubbo
    port: 20880
  scan:
    base-packages: com.chenze.technicalcase.user.service

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://gz-cdb-nf8meuv5.sql.tencentcdb.com:26242/chenze_learning_router?useSSL=true&useUnicode=true&characterEncoding=utf8
    username: root
    password: Cz0523..
  redis:
    port: 6379
    host: 114.96.67.201
    password:
    database: 0
    timeout: 2000
    lettuce:
      pool:
        max-active: 8
        min-idle: 1

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.chenze.technicalcase.user.model.entity
